-- Add mustChangePassword flag on User.
--
-- WHY: seeded accounts (admin/manager/coord) carry a password generated by
-- seed.js and logged once to Railway deploy logs. Anyone who read that log
-- once knows the creds. Forcing rotation on first successful login turns
-- that one-shot exposure into a self-healing window — the window closes
-- the first time the operator signs in and changes the password.
--
-- Default TRUE only for seeded rows is enforced at INSERT time
-- (scripts/seed.js). Existing non-seeded users default to FALSE so they
-- are not surprised by a forced prompt.

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "mustChangePassword" BOOLEAN NOT NULL DEFAULT FALSE;

-- Flag the seeded accounts so the coordinator, manager, and admin are
-- forced to rotate on their first login after this migration. These
-- passwords appeared in Railway deploy logs at seed time, so the forced
-- rotation is a one-way window that closes on first real login.
UPDATE "User"
SET "mustChangePassword" = TRUE
WHERE email IN (
  'admin@opsboard.local',
  'manager@opsboard.local',
  'coord@opsboard.local'
);
